### PR TITLE
Development

### PR DESCRIPTION
**Pull request by phfdonda**
We have completed the TNW clone page and request your code review, we work on this project making use of flex-box like the main approach, this projects these sections:

* Navigation bar
* cover picture
* latest news
* latest funding rounds
* category section
* latest deals
* footer

### CODE REVIEW

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Project requires changes.

**Comment by pelzolga123** [comment]
## Hi Team!  
### Your project looks :+1: amazing!
Just a few small changes before this project can be approved:
* [x] Pull Request should have meaningful title and a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
* [x] Tablet version of navigation bar should look more like original:
image
Original:
image

* [OPTIONAL] It would be better if you made max-width for mobile and tablet versions smaller, because right now, it doesn't display in responsive mode of browser developer tools.

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Comment by rubenpazch** [comment]
We did work on recommendation and fix issues thank you

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
